site_name: Source Mod Wiki

theme: readthedocs

repo_name: "ChocoScaff/source_mod_wiki"
repo_url: https://github.com/ChocoScaff/source_mod_wiki

edit_uri: edit/master/docs/

nav:
    - Branche du moteur: branche.md
    - Répertoire et création d un projet: repertoire_et_creation_dun_projet.md
    - Texture: texture.md
    - Model: model.md
    - Les Outils d'hammer: hammer.md
    - Optimisation: optimisation.md
    - Les entités: entity.md
    - Programmation: programmation.md
    - Ressources: ressource.md
    - Skybox: skybox.md
    - Son et Musique: sons.md
    - Video: video.md
    - Sprinkle: sprinkle.md
    - Particules: particle.md
    - Dialogue: dialogue.md
    - Trigger et algorithme dans hammer: trigger_hammer.md
    - Level design: level_design.md
    - Asset Browser: asset_browser.md
    - Lexique: lexique.md
    - Liens: links.md
    - Problèmes: probleme.md